"""added an action table

Revision ID: 6db061a61f39
Revises: dd4294138fa3
Create Date: 2020-12-06 11:44:05.678173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db061a61f39'
down_revision = 'dd4294138fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=True),
    sa.Column('toxicity', sa.Float(), nullable=True),
    sa.Column('threat', sa.Float(), nullable=True),
    sa.Column('sexually_explicit', sa.Float(), nullable=True),
    sa.Column('profanity', sa.Float(), nullable=True),
    sa.Column('insult', sa.Float(), nullable=True),
    sa.Column('identity_attack', sa.Float(), nullable=True),
    sa.Column('flirtation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('action')
    # ### end Alembic commands ###
