"""drop the wrong one

Revision ID: 8040c0f4bda7
Revises: dd4294138fa3
Create Date: 2020-12-02 12:27:40.119538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8040c0f4bda7'
down_revision = 'dd4294138fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'sexual_explicit')
    op.drop_column('user', 'sexual_explicit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sexual_explicit', sa.FLOAT(), nullable=True))
    op.add_column('post', sa.Column('sexual_explicit', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
